server:
  host: :8086
handler_configs:
  book:
    handler: index
    work_dir: node_modules/@pathserve/client/dist
  vr:
    handler: vite
    work_dir: './'
    watch_dir: './src'
    params:
      html_template: node_modules/@pathserve/client/templates/react-template.html
      script_template: node_modules/@pathserve/client/templates/react-template.tsx
      auto_gen_dir: node_modules/@pathserve/client/autogen
      dir_public: public
      host: http://localhost:5024
host_params:
  - path: node_modules/@pathserve/client/dist/index.html
    key: index
    handler_config: ""