server:
  host: :8085
handler_configs:
  book:
    handler: index
    work_dir: '../client/dist'
  ps:
    handler: vite
    work_dir: '../examples/vite-vue3'
    watch_dir: '../examples/vite-vue3/src'
    params:
      html_template: node_modules/pathserve/templates/template.html
      script_template: node_modules/pathserve/templates/template.ts
      auto_gen_dir: node_modules/pathserve/autogen
      dir_public: ../examples/vite-vue3/public
      host: http://localhost:5023
  vitecfg2:
    handler: vite
    work_dir: '../examples/vite-vue3'
    watch_dir: '../examples/vite-vue3/src'
    params:
      html_template: ../examples/vite-vue3/src/pathserve/templates/template.html
      script_template: ../examples/vite-vue3/src/pathserve/templates/template.ts
      auto_gen_dir: ../examples/vite-vue3/src/pathserve/autogen
      dir_public: ../examples/vite-vue3/public
      host: http://localhost:5023
  index:
    handler: index
    work_dir: '../client/dist'
host_params:
  - path: ./examples/index/index.html
    key: index
    handler_config: index
  - path: ../client/dist/index.html
    key: client
    handler_config: book 
  - path: ../examples/vite-vue3/src/App.vue
    key: vuecomponent
    handler_config: ps