server:
  host: :8085
handler_configs:
  book:
    handler: index
    work_dir: node_modules/pathserve/client
  ps:
    handler: vite
    work_dir: './'
    watch_dir: './src'
    params:
      html_template: node_modules/pathserve/templates/vue3-template.html
      script_template: node_modules/pathserve/templates/vue3-template.ts
      auto_gen_dir: node_modules/pathserve/autogen
      dir_public: public
      host: http://localhost:5023
host_params:
  - path: node_modules/pathserve/client/index.html
    key: index
    handler_config: ""