server:
  host: :8085
handler_configs:
  book:
    handler: index
    work_dir: node_modules/pathserve/client
  ps:
    handler: vite
    work_dir: './'
    watch_dir: './src'
    params:
      params:
      html_template: node_modules/pathserve/templates/template.html
      script_template: node_modules/pathserve/templates/template.ts
      auto_gen_dir: node_modules/pathserve/autogen
      dir_public: public
      host: http://localhost:5023
host_params:
  index: node_modules/pathserve/client/index.html